export enum EVENTS {
  ITEM_ADDED = 'ITEM_ADDED',
  ITEM_UPDATED = 'ITEM_UPDATED',
  ITEM_REMOVED = 'ITEM_REMOVED',
  PROMOTION_APPLIED = 'PROMOTION_APPLIED',
  CHECKOUT_COMPLETED = 'CHECKOUT_COMPLETED',
  CART_EXPIRED = 'CART_EXPIRED'
}
